### ISSUE TITLE
Top Menu Bar Button Alignment Off on Non-Default Font Sizes

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#590] opened 2017-01-15 21:38 UTC
In the attached screenshots, you can see that the button and text in the top menu bar is/are misaligned.  My phone uses the "Small" Android Display font size, and I believe that is what causes this.  Shouldn't this be dynamically centered vertically, or is that not possible/easy?

I'm running version `2.0.0-beta.1`.

<img width=480 src=https://cloud.githubusercontent.com/assets/1566689/21966414/490a93a4-db38-11e6-9739-b7d801ea1341.png>
<img width=480 src=https://cloud.githubusercontent.com/assets/1566689/21966412/49075f2c-db38-11e6-90f0-9648fdce4a0e.png>
<img width=480 src=https://cloud.githubusercontent.com/assets/1566689/21966413/490a85a8-db38-11e6-9861-9e5245f17d69.png>
<img width=480 src=https://cloud.githubusercontent.com/assets/1566689/21966415/490d2f92-db38-11e6-8a9c-44ed1d6dcf1a.png>

**Comment by hawkrives** [comment] 2017-01-15 21:39
You would think that it would be easy, wouldn't you? I would have expected that. 

I'll take another stab at it and see if I can make the computer center them vertically instead of the current method of tweaking pixel values. 

Thanks for reporting! We'll see if we can't get this fixed in the next release.

**Comment by hawkrives** [comment] 2017-01-15 22:14
@drewvolz, @elijahverdoorn We should remember to test v2.1 with alternate font sizes.

**Comment by hawkrives** [comment] 2017-01-18 16:47
Me, in Slack:

> A quick update on https://github.com/StoDevX/AAO-React-Native/issues/590: The issue is that we respect dynamic font sizes on the navbar. I've checked stock iOS apps, and they don't change the font size on the navbar; I haven't checked on Android yet, but I wouldn't be surprised if they do the same.
> 
> Therefore, I propose that we set `allowFontScaling={false}` on our navbar components. (Where, exactly, is tbd.)
> 
> The biggest problem with that, is that said property is only respected on iOS. Or, it was, until https://github.com/facebook/react-native/commit/4394419b60c7dfe5287e5e3f897e855eb7dc57c2 happened. Unfortunately, said commit is only in v0.41-pre, _but_ it seems pretty self-contained.
> 
> So, I wrote a little script to apply that patch to our node_modules folder. I'll test with it this evening, but I hope that we'll be able to just apply that patch and avoid font scaling issues on iOS/android navbars! (Unless the patch horribly breaks something else, but it doesn't look like it touches much.)

**Comment by hawkrives** [comment] 2017-01-21 01:12
@rye – I'm sorry, but I don't think this is going to make this release. Hopefully I can figure it out and we can cut another release with it fixed 😕

**Comment by rye** [comment] 2017-01-23 14:51
@hawkrives, there is a chance that this has something to do with the disparity between px, pt, dp, and sp.  If you're using px as your font size unit&mdash;or, if you're not specifying and the default for size measurements is px&mdash;then I think that'll cause this problem.  ([further reading](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size), [more apposite](http://stackoverflow.com/questions/2025282/what-is-the-difference-between-px-dp-dip-and-sp-on-android))

The simplest solution would probably be to make sure you're using the same units everywhere, and if you're using px switch to something that is not px.  I'd recommend pt from personal experience in web design, since a pt represents an actual real distance measurement independent of screen scaling.

Let me know if there's anything I can do to help test.

**Comment by hawkrives** [comment] 2017-01-23 15:38
Yeah. Problem is, React native uses px implicitly, I believe (or it might be pt on android). Point is, I get to give it a number, and no unit, so I can't control that. (The labels are also positioned with position:absolute, which leads to our title overlap issues on iOS... but they make use of that feature to do the transition animations between screens on iOS. Otherwise, I'd just be be able to do align-items:center and be done with the thing...)

Now. I wonder if I can make Android use the React Native `ToolbarAndroid` on android? I expect that it would center properly... 

I'll look into enabling TestFlight for Android and signing the betas so that they actually run. 

---

The problem is, it doesn't seem like _anyone_ really cares about making React Native apps _feel_ native. Heck, Facebook Groups for iOS has a back button – but it moves up and down between pages! Anyway. 

React Native has a component called NavigatorExperimental, which seems to not have issues centering (at least on iOS). I would like to switch to that, since they're signaling that it will become the preferred navigation solution at some point. That's something I'll investigate after this release.

**Comment by elijahverdoorn** [comment] 2017-01-23 18:05
I agree with @hawkrives about people not really caring about native-feeling apps. I think this is a symptom the comes from most of the developers of RN apps being web developers (with web react) that are making the transition to native, and they'd rather bring their ideas about how to do design with them from the web and skip learning the Material design / iOS design patterns. I think that there's a case for that, but given the direction of AAO and the work that has already been put in to making it as "native" as possible to each platform I'd like to continue down this path. As the platform matures and pulls more traditional native developers into the ecosystem I think the tooling for native-feeling apps will get better. We're on the cutting edge here, and sometimes we have to pay the tax on that: this is one of those times.

**Closed as completed** 2017-06-15 01:13 UTC
Labels: bug/general, status/has-pr, bug/layout

**Comment by rye** [comment] 2017-06-15 01:29
😍
