### ISSUE TITLE
Calendar Returns "Bad Request" on Android

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#186] opened 2016-08-31 18:18 UTC
In some instances of the limited number of devices that I have tested on thus far, the calendar returns the text "bad request" every time it is loaded on both tabs.

**Comment by drewvolz** [comment] 2016-08-31 18:24
https://developers.google.com/google-apps/calendar/v3/errors#400_bad_request

**Comment by drewvolz** [comment] 2016-10-07 04:40
Checking in on this one. Did you ever find the root cause?

**Comment by elijahverdoorn** [comment] 2016-10-07 06:24
No, I haven't, The digging that I've done leads me to believe that it has something to do with usage limits, but that contradicts the fact that all the iOS devices are using it fine. I'm tempted to change keys and see what happens; one solution that I came up with was to use a separate key for iOS and Android, since I think just changing the key _might_ fix the issue?

**Comment by drewvolz** [comment] 2016-11-10 20:20
If this is a cause of rate limiting, we should approach it via your idea of dual API keys. Otherwise, I feel we can close this issue, unless anyone else feels differently.

**Comment by elijahverdoorn** [comment] 2016-11-11 19:45
It's still an issue, since the calendar is not working. I'll try to fix this one.

**Comment by hawkrives** [comment] 2016-11-11 19:50
@elijahverdoorn Does this happen a) on the released build and b) every time you try to use the calendar?

**Comment by elijahverdoorn** [comment] 2016-11-11 20:15
@hawkrives Yes to both.

**Comment by hawkrives** [comment] 2016-11-11 20:40
… so I would have sworn that it was working on my android phone, but I just checked and I can reproduce this, as well.

**Comment by hawkrives** [comment] 2016-11-11 22:30
@elijahverdoorn What version of android is your phone running? The calendar fails on my Galaxy S3 (android 5), but works properly on the sim (android 6).

I am spinning up an android 5 and android 4.3 simulator now, to test.

**Comment by hawkrives** [comment] 2016-11-11 23:33
Ok. Bad news: the 5.1 simulator works correctly.

Continuing to debug.

**Comment by hawkrives** [comment] 2016-11-11 23:44
Debugging has finished. Writing up now.

**Comment by hawkrives** [comment] 2016-11-11 23:48
It works from `master` on-device. I don't know when it was fixed, or what fixed it – maybe the rn upgrade? – but it works for me now, and the released copy wasn't working on this same hardware. (Apologies for the sideways picture.)

![img_7501](https://cloud.githubusercontent.com/assets/464441/20233588/cf733598-a836-11e6-9487-8b7506fa78ec.JPG)

**Comment by elijahverdoorn** [comment] 2016-11-14 00:25
I'll take it. I haven't put much time into it other than to gen some new keys which I was going to put into a testing build, so nothing much lost. Let's close this one and re-open if it resurfaces?

**Comment by hawkrives** [comment] 2016-11-14 00:31
Sounds good to me.

**Closed as completed** 2016-11-14 00:30 UTC
Labels: bug/general
