### ISSUE TITLE
KSTO reports "offline" when it is online

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1616] opened 2017-09-16 21:38 UTC
I am checking on the `chunklist` data and we seem to have data, so I'm unsure why the promise would timeout. 

``` bash
curl -X GET https://cdn.stobcm.com/radio/ksto1.stream/chunklist.m3u8

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:14113
#EXTINF:10.031,
media-uqyghdrhx_14113.mp3
#EXTINF:10.031,
media-uqyghdrhx_14114.mp3
#EXTINF:9.953,
media-uqyghdrhx_14115.mp3
```

Debugging a little, I can see we're ending up in the `catch` of the promise 
https://github.com/StoDevX/AAO-React-Native/blob/a418b0b0df130a149e37844d036a3e306c708e48/source/lib/promise-timeout.js#L18-L21

Landscape | Portrait
---|---
<img width="707" alt="screen shot 2017-09-16 at 5 21 58 pm" src="https://user-images.githubusercontent.com/5240843/30516201-a742e6dc-9b05-11e7-9a06-0d8558d2dc02.png"> | <img width="397" alt="screen shot 2017-09-16 at 5 22 18 pm" src="https://user-images.githubusercontent.com/5240843/30516202-a7447dda-9b05-11e7-832a-9fdd439a51e1.png">

**Comment by hawkrives** [comment] 2017-09-17 00:09
@drewvolz I cannot reproduce this.

**Comment by hawkrives** [comment] 2017-09-17 00:09
… uh. I switched back to the sim after writing that comment…

<img width="375" alt="screen shot 2017-09-16 at 7 09 17 pm" src="https://user-images.githubusercontent.com/464441/30516919-8ddc0c70-9b12-11e7-8349-2604b6dac39c.png">

**Comment by hawkrives** [comment] 2017-09-17 01:57
I'm tired of `react-native-video`. I have now made a solution that doesn't use it. PR coming shortly.

**Comment by hawkrives** [comment] 2017-09-17 18:15
I'm going to declare this closed by way of https://github.com/StoDevX/AAO-React-Native/pull/1623

**Closed as completed by hawkrives** 2017-09-17 18:15 UTC
Labels: bug/general, status/has-pr
