### ISSUE TITLE
Navigation and status bar clobber each other when app starts in landscape

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1908] opened 2017-11-19 08:17 UTC
If the app is started in landscape, every view displays the status bar and the navigation bar. I am attaching the home view as an example.

![65dfb93b-cbdc-49cc-9306-e7c70dcd01ba](https://user-images.githubusercontent.com/5240843/32988737-66a9654e-ccc7-11e7-87ef-909ba61b6953.png)

**Comment by hawkrives** [comment] 2018-01-05 20:36
@drewvolz Does this still happen with today's beta? I ask because we've had two react-navigation updates recently, and my gut says this is a problem in that lib.

**Comment by hawkrives** [comment] 2018-01-05 20:37
We can probably also work around this in `<App/>`'s componentDidMount, with a combination of knowing our orientation and using the `StatusBar.setHidden(true)` method (https://facebook.github.io/react-native/docs/statusbar.html#docsNav)

I'm leaving this in the 2.5 milestone because I think there's a workaround.

**Comment by drewvolz** [comment] 2018-01-05 20:40
I believe this is fixed.

**Comment by hawkrives** [comment] 2018-01-05 20:41
I also cannot reproduce. Closing.

**Closed as completed by hawkrives** 2018-01-05 20:41 UTC
Labels: bug/layout, platform/ios
