### ISSUE TITLE
Filter view is empty on android course search

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2420] opened 2018-03-12 14:00 UTC
1 | 2
--|--
<img width="447" alt="android-filter-course" src="https://user-images.githubusercontent.com/5240843/37287864-6980df88-25cb-11e8-9d1c-5116df2b493f.png"> | <img width="447" alt="android-course-search" src="https://user-images.githubusercontent.com/5240843/37287934-985672dc-25cb-11e8-8721-f524770eff28.png">

**Comment by drewvolz** [comment] 2018-03-12 14:02
I'm also running across this on the android course search.

<img width="447" alt="android-course-search" src="https://user-images.githubusercontent.com/5240843/37287934-985672dc-25cb-11e8-8721-f524770eff28.png">

**Comment by hawkrives** [comment] 2018-03-12 15:05
The second is the cause of the first

**Comment by hannesmcman** [comment] 2018-03-14 01:39
Do you always get that? Works fine on my android emulator..

**Comment by drewvolz** [comment] 2018-03-14 01:58
I always receive it on my emu and physical phone

**Comment by hannesmcman** [comment] 2018-05-07 19:33
@drewvolz How's the debugging of this issue going? I have still not been able to reproduce it..

**Comment by drewvolz** [comment] 2018-05-07 19:36
Looking at the screenshots, it's the same error as https://github.com/StoDevX/AAO-React-Native/issues/2502

**Comment by hannesmcman** [comment] 2018-05-07 19:40
Oh, ok. I'm going to close this issue as a duplicate of #2502 if that's ok.

**Closed as completed by hannesmcman** 2018-05-07 19:40 UTC
Labels: bug/general, bug/layout, platform/android
